const dummyContents = [
    { body: '나는 연화라는 이름을 잘도 마음에 들어한다', type: 'text' },
    { body: '', type: 'text' },
    { body: '', type: 'text' },
    { body: '', type: 'text' },
    { body: '', type: 'text' },
    { body: '', type: 'text' },
    { body: '자켓에 대하여', type: 'heading' },
    { body: '', type: 'text' },
    { body: '', type: 'text' },
    { body: 'Why diary?', type: 'heading' },
    { body: 'img1', type: 'image' },
    { body: '', type: 'text' },
    { body: '앉을 자리를 찾는다면 유체역학 서가 사이가 좋습니다', type: 'text' },
    { body: '', type: 'text' },
    { body: '', type: 'text' },
    { body: 'img2', type: 'image' },
    { body: 'img3', type: 'image' },
    { body: '미숙한 음성이 줄곧 좋았다고', type: 'text' },
    { body: '', type: 'text' },
    { body: '', type: 'text' },
    { body: '', type: 'text' },
    { body: '카뮈 마저 여름과 결혼을 적었고', type: 'text' },
    { body: 'Monthly를 성공시킬 수 있다면 군대를 미루자', type: 'text' },
    { body: '', type: 'text' },
    { body: '', type: 'text' },
    { body: '', type: 'text' },
    { body: '', type: 'text' },
    { body: '', type: 'text' },
    { body: '', type: 'text' },
    { body: '', type: 'text' },
    { body: '', type: 'text' },
];

export default dummyContents;